the_shop/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'


urlpatterns = [
    path('sign_up/', views.sign_up, name="sign_up"),
    path('check_email_to_log_in/', views.signup_redirect, name="redirect"),
    path('log_in/', views.log_in, name="log_in"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('profile_details/', views.profile_details, name="profile_details"),
    path('password_change/', views.password_change, name='password_change'),
    path('password_changed_check_email_to_log_in/', views.password_change_redirect, name="password_changed"),
    path('delete_profile_picture/', views.delete_profile_picture, name="delete_profile_picture"),
    path('log_out/', views.log_out, name="log_out"),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name="password_reset_complete")
]

the_shop/brands/urls.py
from django.urls import path
from . import views

app_name = 'brands'

urlpatterns = [
    path('Jordans/', views.jordans, name="Jordans"),
    path('Nikes/', views.nikes, name="Nikes"),
    path('Vans/', views.vans, name="Vans"),
    path('Yeezys/', views.yeezys, name="Yeezys"),
    path('Pradas/', views.pradas, name="Pradas"),
    path('Shoes Accessories/', views.shoes_accessories, name="Shoes Accessories"),
    path('Pumas/', views.pumas, name="Pumas"),
    path('Balenciagas/', views.balenciagas, name="Balenciagas"),
    path('Gucci/', views.gucci, name="Gucci"),
    path('Louis Vuitton/', views.louis_vuitton, name="Louis Vuitton"),
    path('Versace/', views.versace, name="Versace"),
    path('Addidas/', views.addidas, name="Addidas"),
    path('', views.catalogue, name="catalogue"),
    path('size-guide/', views.size_guide, name="size_guide")
]

the_shop/the_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('top_shop.urls')),
    path('shop_services/', include('shop_services.urls')),
    path('catalogue/', include('brands.urls')),
    path('account/', include('accounts.urls')),
    path('orders/', include('theorders.urls')),
    path('account/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

the_shop/brands/models.py
from django.db import models
import datetime


class Brand(models.Model):
    brand_image = models.ImageField(upload_to='brand-logo/', default='assets/zebby.jpg')
    brand_name = models.CharField(max_length=256)
    brand_description = models.TextField()
    no_of_shoes_available = models.PositiveIntegerField()
    brand_in_stock = models.BooleanField(default=False)
    time = models.DateTimeField(auto_now=datetime.datetime.now)

    def __str__(self):
        return self.brand_name


class Color(models.Model):
    color_name = models.TextField(max_length=50)
    time_added = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.color_name


class Size(models.Model):
    size_number = models.CharField(max_length=50)
    time_added = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.size_number


class Product(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True)
    shoe_image = models.ImageField(upload_to='shoes/', height_field='image_height', width_field='image_width')
    image_height = models.PositiveIntegerField(blank=True, null=True)
    image_width = models.PositiveIntegerField(blank=True, null=True)
    shoe_name = models.CharField(max_length=256)
    shoe_size = models.ManyToManyField(Size, blank=True)
    shoe_gender = models.TextField()
    shoe_color_available = models.ManyToManyField(Color)
    shoe_price = models.DecimalField(decimal_places=2, max_digits=9)
    shoe_in_stock = models.BooleanField(default=False)
    shoe_price_was = models.DecimalField(blank=True, null=True, decimal_places=2, max_digits=9)
    shoe_time_added = models.DateTimeField(auto_now=datetime.datetime.now)

    def __str__(self):
        return self.shoe_name

the_shop/brands/views.py
from django.shortcuts import render
from .models import Brand, Product, Size
from django.shortcuts import get_object_or_404
from theorders.models import Order


def catalogue(request):
    shop_brands = Brand.objects.all().order_by('-brand_in_stock', '-time')
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(user=customer, complete=False)
        return render(request, 'catalogue.html', {"shop_brands": shop_brands, "order": order})
    return render(request, 'catalogue.html', {"shop_brands": shop_brands})


def jordans(request):
    jordan_brand = get_object_or_404(Brand, brand_name='Jordans')
    jordan_shoes = Product.objects.filter(brand=jordan_brand).order_by('-shoe_in_stock', '-shoe_time_added')
    # size = Size.objects.all().order_by('-time_added')
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(user=customer, complete=False)
        return render(request, 'jordans.html', {
            "jordan_shoes": jordan_shoes,
            "order": order,
        })
    return render(request, 'jordans.html', {
        "jordan_shoes": jordan_shoes,
    })


def nikes(request):
    nike_brand = get_object_or_404(Brand, brand_name='Nikes')
    nike_shoes = Product.objects.filter(brand=nike_brand).order_by('-shoe_in_stock', '-shoe_time_added')
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(user=customer, complete=False)
        return render(request, 'nikes.html', {"nike_shoes": nike_shoes, "order": order})
    return render(request, 'nikes.html', {"nike_shoes": nike_shoes})


def vans(request):
    vans_brand = get_object_or_404(Brand, brand_name='Vans')
    vans_shoes = Product.objects.filter(brand=vans_brand).order_by('-shoe_in_stock', '-shoe_time_added')
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(user=customer, complete=False)
        return render(request, 'vans.html', {"vans_shoes": vans_shoes, "order": order})
    return render(request, 'vans.html', {"vans_shoes": vans_shoes})


def yeezys(request):
    yeezy_brand = get_object_or_404(Brand, brand_name='Yeezys')
    yeezy_shoes = Product.objects.filter(brand=yeezy_brand).order_by('-shoe_in_stock', '-shoe_time_added')
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(user=customer, complete=False)
        return render(request, 'yeezys.html', {"yeezy_shoes": yeezy_shoes, "order": order})
    return render(request, 'yeezys.html', {"yeezy_shoes": yeezy_shoes})


def pradas(request):
    prada_brand = get_object_or_404(Brand, brand_name='Pradas')
    prada_shoes = Product.objects.filter(brand=prada_brand).order_by('-shoe_in_stock', '-shoe_time_added')
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(user=customer, complete=False)
        return render(request, 'pradas.html', {"prada_shoes": prada_shoes, "order": order})
    return render(request, 'pradas.html', {"prada_shoes": prada_shoes})


def shoes_accessories(request):
    shoes_accessories_brand = get_object_or_404(Brand, brand_name='Shoes Accessories')
    shoes_accessories_products = Product.objects.filter(brand=shoes_accessories_brand).order_by('-shoe_in_stock', '-shoe_time_added')
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(user=customer, complete=False)
        return render(request, 'shoes_accessories.html', {"shoes_accessories_products": shoes_accessories_products, "order": order})
    return render(request, 'shoes_accessories.html', {"shoes_accessories_products": shoes_accessories_products})


def pumas(request):
    puma_brand = get_object_or_404(Brand, brand_name='Pumas')
    puma_shoes = Product.objects.filter(brand=puma_brand).order_by('-shoe_in_stock', '-shoe_time_added')
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(user=customer, complete=False)
        return render(request, 'pumas.html', {
            "puma_shoes": puma_shoes,
            "order": order
        })
    return render(request, 'pumas.html', {
        "puma_shoes": puma_shoes
    })


def balenciagas(request):
    balenciaga_brand = get_object_or_404(Brand, brand_name='Balenciagas')
    balenciaga_shoes = Product.objects.filter(brand=balenciaga_brand)
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(user=customer, complete=False)
        return render(request, 'balenciagas.html', {
            "balenciaga_shoes": balenciaga_shoes,
            "order": order
        })
    return render(request, 'balenciagas.html', {
        "balenciaga_shoes": balenciaga_shoes
    })


def gucci(request):
    gucci_brand = get_object_or_404(Brand, brand_name="Gucci")
    gucci_shoes = Product.objects.filter(brand=gucci_brand)
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(user=customer, complete=False)
        return render(request, 'gucci.html', {
            "gucci_shoes": gucci_shoes,
            "order": order
        })
    return render(request, 'gucci.html', {
        "gucci_shoes": gucci_shoes
    })


def louis_vuitton(request):
    louis_vuitton_brand = get_object_or_404(Brand, brand_name="Louis Vuitton")
    louis_vuitton_shoes = Product.objects.filter(brand=louis_vuitton_brand)
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(user=customer, complete=False)
        return render(request, 'louis_vuitton.html', {
            "louis_vuitton_shoes": louis_vuitton_shoes,
            "order": order
        })
    return render(request, 'louis_vuitton.html', {
        "louis_vuitton_shoes": louis_vuitton_shoes
    })


def versace(request):
    versace_brand = get_object_or_404(Brand, brand_name="Versace")
    versace_shoes = Product.objects.filter(brand=versace_brand)
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(user=customer, complete=False)
        return render(request, 'versace.html', {
            "versace_shoes": versace_shoes,
            "order": order
        })
    return render(request, 'versace.html', {
        "versace_shoes": versace_shoes
    })


def addidas(request):
    addidas_brand = get_object_or_404(Brand, brand_name="Addidas")
    addidas_shoes = Product.objects.filter(brand=addidas_brand)
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(user=customer, complete=False)
        return render(request, 'addidas.html', {
            "addidas_shoes": addidas_shoes,
            "order": order
        })
    return render(request, 'addidas.html', {
        "addidas_shoes": addidas_shoes
    })


def size_guide(request):
    customer = request.user
    if request.user.is_authenticated:
        order, created = Order.objects.get_or_create(user=customer, complete=False)
        return render(request, 'size_guide.html', {"order": order})
    return render(request, 'size_guide.html')

the_shop/brands/templates/addidas.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ADDIDAS</title>
    <link rel="shortcut icon" href="{% static 'logo.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/page-header.css' %}">
    <link rel="stylesheet" href="{% static 'css/add_to_cart_button.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css"/>
</head>
<body>
{% if user.is_authenticated %}
    <script src="{% static 'js/csrf_token.js' %}"></script>
{% endif %}

{% include 'bootstrap.html' %}
{% include 'backToTop.html' %} <!-- Back to Top button -->
<!-- ADDIDAS SHOES -->
<br><br>
<div class="container">
    <div class="custom-container">
        <h3 class="display-3">
            <strong>ADDIDAS SHOES</strong>
        </h3>
    </div>
    <br><br>
    <!-- SEARCH BUTTON----JS IN assets/search.js -->
    <div class="d-flex justify-content-center">
        <form class="d-flex" role="search" style="width: 50%;" onsubmit="event.preventDefault(); performSearch();">
            <input class="form-control me-2" type="search" placeholder="search" aria-label="Search" id="search-input">
            <button id="search-button" class="btn btn-outline-secondary" type="submit">
                <i class="fa fa-search"></i>
            </button>
        </form>
    </div>
    <br>
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4 d-flex">
        {% for all_shoes in addidas_shoes %}
        <div class="col">
            <div class="card">
                <img src="{{ all_shoes.shoe_image.url }}" class="card-img-top" alt="shoe" style="object-fit: cover; width: 100%; height: 250px;">
                <div class="card-body">
                    <h5 class="card-title">{{ all_shoes.shoe_name }}</h5>
                    <p class="card-text">{{ all_shoes.shoe_gender }}</p>
                    <div style="flex:3"><strong><a href="{% url 'brands:size_guide' %}" style="text-decoration:none;" class="add-to-cart">Find the perfect size</a></strong></div>
                    <div style="flex:3">
                        <div>
                            <label for="size-filter"></label>
                            <select id="size-filter">
                                <option value="all">Select Size</option>
                                {% for sizes in size %}
                                <option value="{{ sizes.size_number }}">{{ sizes.size_number }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    {% for color in all_shoes.shoe_color_available.all %}
                    <p class="card-text">{{ color.color_name }}</p>
                    {% endfor %}
                    <p class="card-text"><strong>Now: ${{ all_shoes.shoe_price }}</strong><br><em>Was:<s> ${{ all_shoes.shoe_price_was }}</s></em></p>
                    {% if all_shoes.shoe_in_stock %}
                        <p>In stock</p>
                        <div class="row">
                            <div class="col">
                                {% if not user.is_authenticated %}
                                    <form action="{% url 'accounts:log_in' %}" method="get" id="login-form">
                                        <input type="hidden" name="next" value="{{ request.path }}">
                                        <button data-product="{{ all_shoes.id }}" data-action="add" class="btn btn-outline-success add-to-cart add-btn update-cart">Add to cart</button>
                                    </form>
                                {% else %}
                                    <button id="liveToastBtn" data-product="{{ all_shoes.id }}" data-action="add" class="btn btn-outline-success add-to-cart add-btn update-cart">Add to cart</button>
                                        <div style="position: fixed; bottom: 50%; right: 0; transform: translate(0, 50%); color: grey;" class="toast-container p-3">
                                            <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="4000">
                                                {% include 'live_toast.html' %}
                                            </div>
                                        </div>
                                {% endif %}
                            </div>
                            <div class="col">
                                <a href="{{ all_shoes.shoe_image.url }}" class="btn btn-outline-secondary add-to-cart">View</a>
                            </div>
                        </div>
                    {% else %}
                        <p><b><s>SOLD OUT</s></b></p>
                        <div class="row">
                            <div class="col">
                                <a class="btn btn-outline-success add-to-cart disabled">Add to cart</a>
                            </div>
                            <div class="col">
                                <a class="btn btn-outline-secondary add-to-cart disabled">View</a>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<script src="{% static 'js/cart.js' %}"></script>
<script src="{% static 'js/search.js' %}"></script>
<script src="{% static 'js/live_toast.js' %}"></script>
<br><br><br>
{% include 'baseshop_footer.html' %}
</body>
</html>

the_shop/brands/templates/balenciagas.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BALENCIAGA</title>
    <link rel="shortcut icon" href="{% static 'logo.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/page-header.css' %}">
    <link rel="stylesheet" href="{% static 'css/add_to_cart_button.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css"/>
</head>
<body>
{% if user.is_authenticated %}
    <script src="{% static 'js/csrf_token.js' %}"></script>
{% endif %}

{% include 'bootstrap.html' %}
{% include 'backToTop.html' %} <!-- Back to Top button -->
<!-- BALENCIAGA SHOES -->
<br><br>
<div class="container">
    <div class="custom-container">
        <h3 class="display-3">
            <strong>BALENCIAGA SHOES</strong>
        </h3>
    </div>
    <br><br>
    <!-- SEARCH BUTTON----JS IN assets/search.js -->
    <div class="d-flex justify-content-center">
        <form class="d-flex" role="search" style="width: 50%;" onsubmit="event.preventDefault(); performSearch();">
            <input class="form-control me-2" type="search" placeholder="search" aria-label="Search" id="search-input">
            <button id="search-button" class="btn btn-outline-secondary" type="submit">
                <i class="fa fa-search"></i>
            </button>
        </form>
    </div>
    <br>
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4 d-flex">
        {% for all_shoes in balenciaga_shoes %}
        <div class="col">
            <div class="card">
                <img src="{{ all_shoes.shoe_image.url }}" class="card-img-top" alt="shoe" style="object-fit: cover; width: 100%; height: 250px;">
                <div class="card-body">
                    <h5 class="card-title">{{ all_shoes.shoe_name }}</h5>
                    <p class="card-text">{{ all_shoes.shoe_gender }}</p>
                    <div style="flex:3"><strong><a href="{% url 'brands:size_guide' %}" style="text-decoration:none;" class="add-to-cart">Find the perfect size</a></strong></div>
                    <div style="flex:3">
                        <div>
                            <label for="size-filter"></label>
                            <select id="size-filter">
                                <option value="all">Select Size</option>
                                {% for sizes in size %}
                                <option value="{{ sizes.size_number }}">{{ sizes.size_number }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <br>
                    {% for color in all_shoes.shoe_color_available.all %}
                    <p class="card-text">{{ color.color_name }}</p>
                    {% endfor %}
                    <p class="card-text"><strong>Now: ${{ all_shoes.shoe_price }}</strong><br><em>Was:<s> ${{ all_shoes.shoe_price_was }}</s></em></p>
                    {% if all_shoes.shoe_in_stock %}
                        <p>In stock</p>
                        <div class="row">
                            <div class="col">
                                {% if not user.is_authenticated %}
                                    <form action="{% url 'accounts:log_in' %}" method="get" id="login-form">
                                        <input type="hidden" name="next" value="{{ request.path }}">
                                        <button data-product="{{ all_shoes.id }}" data-action="add" class="btn btn-outline-success add-to-cart add-btn update-cart">Add to cart</button>
                                    </form>
                                {% else %}
                                    <button id="liveToastBtn" data-product="{{ all_shoes.id }}" data-action="add" class="btn btn-outline-success add-to-cart add-btn update-cart">Add to cart</button>
                                        <div style="position: fixed; bottom: 50%; right: 0; transform: translate(0, 50%); color: grey;" class="toast-container p-3">
                                            <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="4000">
                                                {% include 'live_toast.html' %}
                                            </div>
                                        </div>
                                {% endif %}
                            </div>
                            <div class="col">
                                <a href="{{ all_shoes.shoe_image.url }}" class="btn btn-outline-secondary add-to-cart">View</a>
                            </div>
                        </div>
                    {% else %}
                        <p><b><s>SOLD OUT</s></b></p>
                        <div class="row">
                            <div class="col">
                                <a class="btn btn-outline-success add-to-cart disabled">Add to cart</a>
                            </div>
                            <div class="col">
                                <a class="btn btn-outline-secondary add-to-cart disabled">View</a>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<script src="{% static 'js/cart.js' %}"></script>
<script src="{% static 'js/search.js' %}"></script>
<script src="{% static 'js/live_toast.js' %}"></script>
<br><br><br>
{% include 'baseshop_footer.html' %}
</body>
</html>

the_shop/brands/templates/gucci.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GUCCI</title>
    <link rel="shortcut icon" href="{% static 'logo.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/page-header.css' %}">
    <link rel="stylesheet" href="{% static 'css/add_to_cart_button.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css"/>
</head>
<body>
{% if user.is_authenticated %}
    <script src="{% static 'js/csrf_token.js' %}"></script>
{% endif %}

{% include 'bootstrap.html' %}
{% include 'backToTop.html' %} <!-- Back to Top button -->
<!-- GUCCI SHOES -->
<br><br>
<div class="container">
    <div class="custom-container">
        <h3 class="display-3">
            <strong>GUCCI SHOES</strong>
        </h3>
    </div>
    <br><br>
    <!-- SEARCH BUTTON----JS IN assets/search.js -->
    <div class="d-flex justify-content-center">
        <form class="d-flex" role="search" style="width: 50%;" onsubmit="event.preventDefault(); performSearch();">
            <input class="form-control me-2" type="search" placeholder="search" aria-label="Search" id="search-input">
            <button id="search-button" class="btn btn-outline-secondary" type="submit">
                <i class="fa fa-search"></i>
            </button>
        </form>
    </div>
    <br>
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4 d-flex">
        {% for all_shoes in gucci_shoes %}
        <div class="col">
            <div class="card">
                <img src="{{ all_shoes.shoe_image.url }}" class="card-img-top" alt="shoe" style="object-fit: cover; width: 100%; height: 250px;">
                <div class="card-body">
                    <h5 class="card-title">{{ all_shoes.shoe_name }}</h5>
                    <p class="card-text">{{ all_shoes.shoe_gender }}</p>
                    <div style="flex:3"><strong><a href="{% url 'brands:size_guide' %}" style="text-decoration:none;" class="add-to-cart">Find the perfect size</a></strong></div>
                    <div style="flex:3">
                        <div>
                            <label for="size-filter"></label>
                            <select id="size-filter">
                                <option value="all">Select Size</option>
                                {% for sizes in size %}
                                <option value="{{ sizes.size_number }}">{{ sizes.size_number }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <br>
                    {% for color in all_shoes.shoe_color_available.all %}
                    <p class="card-text">{{ color.color_name }}</p>
                    {% endfor %}
                    <p class="card-text"><strong>Now: ${{ all_shoes.shoe_price }}</strong><br><em>Was:<s> ${{ all_shoes.shoe_price_was }}</s></em></p>
                    {% if all_shoes.shoe_in_stock %}
                        <p>In stock</p>
                        <div class="row">
                            <div class="col">
                                {% if not user.is_authenticated %}
                                    <form action="{% url 'accounts:log_in' %}" method="get" id="login-form">
                                        <input type="hidden" name="next" value="{{ request.path }}">
                                        <button data-product="{{ all_shoes.id }}" data-action="add" class="btn btn-outline-success add-to-cart add-btn update-cart">Add to cart</button>
                                    </form>
                                {% else %}
                                    <button id="liveToastBtn" data-product="{{ all_shoes.id }}" data-action="add" class="btn btn-outline-success add-to-cart add-btn update-cart">Add to cart</button>
                                        <div style="position: fixed; bottom: 50%; right: 0; transform: translate(0, 50%); color: grey;" class="toast-container p-3">
                                            <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="4000">
                                                {% include 'live_toast.html' %}
                                            </div>
                                        </div>
                                {% endif %}
                            </div>
                            <div class="col">
                                <a href="{{ all_shoes.shoe_image.url }}" class="btn btn-outline-secondary add-to-cart">View</a>
                            </div>
                        </div>
                    {% else %}
                        <p><b><s>SOLD OUT</s></b></p>
                        <div class="row">
                            <div class="col">
                                <a class="btn btn-outline-success add-to-cart disabled">Add to cart</a>
                            </div>
                            <div class="col">
                                <a class="btn btn-outline-secondary add-to-cart disabled">View</a>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<script src="{% static 'js/cart.js' %}"></script>
<script src="{% static 'js/search.js' %}"></script>
<script src="{% static 'js/live_toast.js' %}"></script>
<br><br><br>
{% include 'baseshop_footer.html' %}
</body>
</html>

the_shop/brands/templates/size_guide.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SIZE GUIDE</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/page-header.css' %}">
    <link rel="shortcut icon" href="{% static 'logo.ico' %}" type="image/x-icon">
</head>
<body>
{% include 'bootstrap.html' %}
{% include 'backToTop.html' %} <!-- Back to Top button -->
<br><br>
<div class="container">
    <h3 class="display-3 custom-container">
        <strong>SIZE GUIDE</strong>
    </h3><!-- page-header.css for custom container styling -->
</div>
<br><br>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8 text-center">
            <h4 class="display-4"><b>HOW TO MEASURE</b></h4>
        </div>
    </div>
</div>
<br><br>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8 text-center">
            <p>
                In order to select the correct shoe size, we recommend you measure your feet using the following guidelines.
            </p>
        </div>
    </div>
</div>
<br>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-6 text-center">
            <img src="{% static 'size-guide.jpg' %}" style="object-fit: cover; width: 100%; max-height: 300px;">
        </div>
    </div>
</div>
<br>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-8 text-center">
            <p>Wear the kind of socks or tights you would normally wear with this type of shoe.</p><br>
            <p>Stand up straight on a flat surface with your heel against a wall. If necessary, ask someone else to help you take the measurements.</p><br>
            <p>Measure from the base of your heel, keeping it pressed against the wall, to the tip of your longest toe.</p><br>
            <p><b>Always measure both feet and use your longest foot as your benchmark.</b></p>
        </div>
    </div>
</div>
<br><br>
{% include 'baseshop_footer.html' %}
</body>
</html>