the_shop/brands/urls.py
from django.urls import path
from . import views

app_name = 'brands'

urlpatterns = [
    path('Jordans/', views.jordans, name="Jordans"),
    path('Nikes/', views.nikes, name="Nikes"),
    path('Vans/', views.vans, name="Vans"),
    path('Yeezys/', views.yeezys, name="Yeezys"),
    path('Pradas/', views.pradas, name="Pradas"),
    path('Shoes Accessories/', views.shoes_accessories, name="Shoes Accessories"),
    path('Pumas/', views.pumas, name="Pumas"),
    path('Balenciagas/', views.balenciagas, name="Balenciagas"),
    path('Gucci/', views.gucci, name="Gucci"),
    path('Louis Vuitton/', views.louis_vuitton, name="Louis Vuitton"),
    path('Versace/', views.versace, name="Versace"),
    path('Addidas/', views.addidas, name="Addidas"),
    path('', views.catalogue, name="catalogue"),
    path('size-guide/', views.size_guide, name="size_guide")
]

the_shop/shop_services/urls.py
from django.urls import path
from . import views

app_name = 'servicesPage'

urlpatterns = [
    path('', views.services, name="services-page"),
    path('order-shoes/', views.order_shoes, name="order-shoes"),
    path('trade/', views.trade, name="trade"),
    path('customize_shoes/', views.customize_shoes, name="customize_shoes"),
    path('donate_shoes/', views.donate_shoes, name="donate_shoes"),
    path('customer_service/', views.customer_service, name="customer_service"),
]

the_shop/the_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('top_shop.urls')),
    path('shop_services/', include('shop_services.urls')),
    path('catalogue/', include('brands.urls')),
    path('account/', include('accounts.urls')),
    path('orders/', include('theorders.urls')),
    path('account/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

the_shop/top_shop/urls.py
from django.urls import path
from . import views

app_name = 'introPage'

urlpatterns = [
    path('', views.home, name="home-page"),
    path('about/', views.about, name="about-page"),
    path('contacts/', views.contacts, name="contacts-page"),
    path('team/', views.team, name="team-page"),
]

the_shop/top_shop/models.py
from django.db import models


class Message(models.Model):
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    email = models.EmailField()
    message = models.CharField(max_length=2500)

    def __str__(self):
        return f'A message from {self.email}'

the_shop/top_shop/forms.py
from .models import Message
from django import forms


class MessageForm(forms.ModelForm):
    first_name = forms.CharField(max_length=500, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=500, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(max_length=500, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    message = forms.CharField(max_length=500, widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = Message
        fields = ('first_name', 'last_name', 'email', 'message')

the_shop/top_shop/views.py
from django.shortcuts import render, redirect
from theorders.models import Order, Comment
from .forms import MessageForm
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string
from django.contrib.auth.models import User

# ToDo: 
 #    Create a separate file for such funcs
#       implement func across...already tested
def getTotalCurtItems(user: str):
    order, created = Order.objects.get_or_create(user=user, complete=False)
    return order.get_cart_items


def home(request):
    # # Get the latest shoes for each brand
    # latest_shoes = Product.objects.filter(
    #     brand=OuterRef('brand')
    # ).order_by('-shoe_time_added')
    #
    # # Get the distinct brands with their latest shoes
    # distinct_brands_with_latest_shoes = Product.objects.filter(
    #     shoe_time_added__lte=datetime.now(),  # To avoid future timestamps if any
    # ).annotate(
    #     latest_shoe_id=Subquery(latest_shoes.values('id')[:1])
    # ).values('latest_shoe_id')
    #
    # # Fetch the final queryset with the latest shoes for each brand
    # popular_products = Product.objects.select_related('brand').filter(id__in=distinct_brands_with_latest_shoes.values('latest_shoe_id'))
    shop_testimonies = Comment.objects.all()
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(user=customer, complete=False)
        return render(request, 'home-shop.html', {"order": order, "shop_testimonies": shop_testimonies})
    else:
        return render(request, 'home-shop.html', {"shop_testimonies": shop_testimonies})


def about(request):
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(user=customer, complete=False)
        return render(request, 'about-shop.html', {"order": order})
    else:
        return render(request, 'about-shop.html')


def contacts(request):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            name = "Zebbylion"
            form.save()

            template = render_to_string('message_added_email.html', {
                "first_name": first_name,
                "last_name": last_name,
                "email": email,
                "name": name,
                "message": message
            })
            sent_email = EmailMessage(
                'New message from Top Gz users',
                template,
                settings.EMAIL_HOST_USER,
                ['zebbynjau@gmail.com']
            )
            sent_email.fail_silently = False
            sent_email.send()
            # Email to be sent to message sender
            template2 = render_to_string('message_sent_email.html', {
                "first_name": first_name,
                "message": message,
                "email": email
            })
            sent_email2 = EmailMessage(
                'Your message has been received',
                template2,
                settings.EMAIL_HOST_USER,
                [email]
            )
            sent_email2.fail_silently = False
            sent_email2.send()
            return redirect('introPage:home-page')
    else:
        form = MessageForm()
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(user=customer, complete=False)
        return render(request, 'contacts.html', {"order": order, "form": form})
    else:
        return render(request, 'contacts.html', {"form": form})


def team(request):
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(user=customer, complete=False)
        return render(request, 'team.html', {"order": order})
    else:
        return render(request, 'team.html')


# def testimonies(request):
#     shop_testimonies = Comment.objects.all()
#     return render(request, 'testimonies.html', {"shop_testimonies": shop_testimonies})

the_shop/top_shop/templates/about-shop.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ABOUT US</title>
    <link rel="shortcut icon" href="{% static 'logo.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/page-header.css' %}">
</head>
<body>
{% include 'bootstrap.html' %}
{% include 'backToTop.html' %} <!--Back to Top button -->
<!-- ABOUT PAGE -->
<br><br>
<div class="custom-container">
    <h3 class="display-3">
        <strong>ABOUT US</strong>
    </h3>
</div>
<br><br>
<h3 class="display-3" style="text-align: center; color:gray">
    <strong>THE SHOP</strong>
</h3>
<br><br><br>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <p class="display-6" style="padding-top: 20px; font-size: xx-large">
                Top Gz is an online shoe shop that offers a wide range of high-quality footwear for customers. From stylish sneakers to comfortable sandals, our platform has it all. Our collection is constantly updated with the latest trends and styles to ensure that you can always find the perfect pair of shoes for your needs. With our user-friendly interface, shopping for shoes has never been easier.<br>At Top Gz, we take pride in providing excellent customer service, so you can shop with confidence. Whether you're looking for a specific style or just want to browse, Top Gz is your one-stop-shop for all your shoe needs.
            </p>
        </div>
        <div class="col-md-6" style="padding-top: 20px;">
            <img src="{% static 'About1.jpg' %}" class="figure-img img-fluid rounded" style="width: 100%; height: auto; object-fit: cover;" alt="...">
            <br><br><br><br><br>
        </div>
    </div>
</div>
<h3 class="display-3" style="text-align: center; color:gray">
    <strong>HOW WE WORK</strong>
</h3>
<br><br><br>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <p class="display-6" style="padding-top: 20px; font-size: xx-large">
                Top Gz is an online shoe shop that makes shopping for shoes easy and convenient. Our platform provides customers with a vast selection of footwear, including sneakers, sandals, boots, and more. To begin your shopping experience, simply visit our website and browse through our collection.<br>At Top Gz, we strive to provide the best possible shopping experience, from the convenience of online shopping to our excellent customer service. Whether you're looking for a specific pair of shoes or just want to browse, Top Gz has you covered.
            </p>
        </div>
        <div class="col-md-6" style="padding-top: 20px;">
            <img src="{% static 'About2.jpg' %}" class="figure-img img-fluid rounded" style="width: 100%; height: auto; object-fit: cover;" alt="...">
            <br><br><br><br><br>
        </div>
    </div>
</div>
<h3 class="display-3" style="text-align: center; color:gray">
    <strong>OUR HISTORY</strong>
</h3>
<br><br><br>

<div class="container">
    <p class="display-6" style="padding-top: 20px; font-size: xx-large">
        Top Gz, a renowned shoe shop, was founded in early 2022 by Zebbylion Njau, an enterprising and passionate entrepreneur. With a vision to provide customers with top-quality footwear and exceptional service, Zebbylion embarked on a journey to establish a thriving shoe retail business.
    </p>
    <p class="display-6" style="padding-top: 20px; font-size: xx-large">
        The inception of Top Gz marked a new chapter in the footwear industry. Team's keen understanding of market trends, coupled with his passion for fashion and style, drove the creation of a curated collection of shoes that catered to diverse tastes and preferences. From casual sneakers to elegant dress shoes, Top Gz offered a wide range of options to satisfy every customer's needs.
    </p>
    <p class="display-6" style="padding-top: 20px; font-size: xx-large">
        With the team's commitment to excellence extended beyond the product selection. Recognizing the growing importance of online shopping, he invested in creating a seamless and user-friendly online platform that allowed customers to explore and purchase their favorite shoes conveniently.
    </p>
    <p class="display-6" style="padding-top: 20px; font-size: xx-large">
        With the team's astute business acumen and dedication to customer satisfaction, Top Gz quickly gained popularity and became a trusted destination for shoe enthusiasts. The shop's commitment to quality, style, and exceptional service fostered a loyal customer base and propelled its growth.
    </p>
    <p class="display-6" style="padding-top: 20px; font-size: xx-large">
        Today, Top Gz stands as a testament to Zebbylion's entrepreneurial spirit and unwavering commitment to delivering the best footwear experience to customers. With a strong foundation and a passion for innovation, Top Gz continues to thrive and shape the shoe retail landscape.
    </p>
</div>
<br><br><br>

{% include 'baseshop_footer.html' %}
</body>
</html>

the_shop/top_shop/templates/contacts.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NIKES</title>
    <link rel="shortcut icon" href="{% static 'logo.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/page-header.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>
{% include 'bootstrap.html' %}
{% include 'backToTop.html' %} <!--Back to Top button -->
<!-- CONTACT US -->
<br><br>
<div class="custom-container">
    <h3 class="display-3">
        <strong>CONTACT US</strong>
    </h3>
</div>
<br><br>
<div class="row">
    <div class="col-md-6">
        <form class="site-form" action="{% url 'introPage:contacts-page' %}" method="post">
            {% csrf_token %}
            <em style="font-weight: bold;" class="display-5">Get in touch</em><small style="font-weight: bold;">...Leave a message and we will get back to you</small><br><br>
            <div class="row" style="width: 85%;">
                <div class="col-md-6">
                    <em style="color: grey">First name</em><br>
                    {{ form.first_name }}
                </div>
                <div class="col-md-6">
                    <em style="color: grey">Last name</em><br>
                    {{ form.last_name }}
                </div>
            </div>
            <br>
            <div class="col-md-8">
                <em style="color: grey">Email (<small>make sure its valid</small>)</em><br>
                {{ form.email }}
            </div>
            <br>
            <div style="width: 100%">
                <em style="color: grey">Message</em><br>
                {{ form.message }}
            </div>
            <br>
            <button type="submit" class="btn btn-outline-secondary" style="margin-left: 150px;">Leave a message</button>
        </form>
    </div>
    <div class="col-md-5" style="margin-top: 150px;">
        <p class="d-inline-flex gap-1">
            <button class="btn btn-outline-secondary btn-lg" type="button" data-bs-toggle="collapse" data-bs-target=".multi-collapse" aria-expanded="false" aria-controls="multiCollapseExample1 multiCollapseExample2" style="width: 100%;">Contact Info</button>
        </p>
        <div class="row mt-3">
            <div class="col-12 mb-3">
                <div class="collapse multi-collapse" id="multiCollapseExample1">
                    <div class="card card-body" style="background-color: #1a1a1a;">
                        <a href="mailto:zebbynjau@gmail.com" style="text-decoration: none; color: white; margin-left: 230px;">
                            <i class="fas fa-envelope fa-2x mr-3"></i>
                        </a>
                        <a href="mailto:zebbynjau@gmail.com" style="text-decoration: none; color: white; margin-left: 180px;">zebbynjau@gmail.com</a>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="collapse multi-collapse" id="multiCollapseExample2">
                    <div class="card card-body" style="background-color: #1a1a1a;">
                        <a href="tel:+254719204467" style="text-decoration: none; color: white; margin-left: 230px;">
                            <i class="fas fa-phone fa-2x mr-3"></i>
                        </a>
                        <a href="tel:+254719204467" style="text-decoration: none; color: white; margin-left: 180px;">+254 719 204 467</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

{% include 'baseshop_footer.html' %}
</body>
</html>

the_shop/top_shop/templates/home-shop.html
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>TOP Gz</title>
    <link rel="shortcut icon" href="{% static 'logo.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"/>
    <style>
        .team-img {
          height: 100%;
          width: 100%;
          max-height: 300px;
          object-fit: cover;
        }
        </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css"/>
    <link rel="stylesheet" href="{% static 'css/testimonies.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css"/>
</head>
<body>
{% include 'bootstrap.html' %}
{% include 'backToTop.html' %} <!--Back to Top button -->

<!--Shop Logo -->
<!-- <div style="position: absolute; top: 90; left: 0; width: 100px;">
    <a href="{% url 'introPage:home-page' %}">
        <img src="{% static 'topg-logo.gif' %}" style="width: 75%; top: 90; left: 0;" alt="GIF">
    </a>
</div> -->

<div class="container-fluid py-5">
    <div class="row">
        <div class="col-md-6">
            <p class="display-3 mt-5">
                <br><br>
                <strong style="color:grey"> Improve Your Footwear With Us. </strong>
            </p>
            <br><br>
            <p style="font-family: sans-serif; font-size: xx-large">
                Welcome to Top Gz Shoe Shop, where we are dedicated to providing you with the best shoe shopping experience possible.
            </p>
            <div class="d-flex justify-content-center align-items-center" style="height: 20vh;">
                <a href="{% url 'brands:catalogue' %}">
                    <button type="button" class="btn btn-outline-secondary btn-lg"><strong>Our Catalogue</strong></button>
                </a>
            </div>
            <br>
            <p style="font-family: sans-serif; font-size: xx-large">
                Whether you need help with sizing, recommendations for a specific occasion, or just want to chat about the latest shoe trends, we are here to assist you.
            </p>
            <div class="d-flex justify-content-center align-items-center" style="height: 20vh;">
                <a href="{% url 'servicesPage:customer_service' %}">
                    <button type="button" class="btn btn-outline-secondary btn-lg"><strong>Customer Service</strong></button>
                </a>
            </div>
        </div>
        <div class="col-md-6 mt-3 mt-md-0">
            <img src="{% static 'about.jpg' %}" class="img-fluid" alt="Top Gz">
        </div>
    </div>
</div>

<!--Popular Products -->

<br>
<div class="container">
    <div class="row">
        <div class="col">
            <h3 class="display-5 text-center mt-5"><strong>Popular Products</strong></h3>
        </div>
    </div>
    <br>
    <div class="owl-carousel owl-theme mt-3">
        <div class="item">
            <a href="{% url 'brands:Shoes Accessories' %}" style="text-decoration: none; cursor: grab;">
                <img class="img-fluid" src="media/shoes/Inner_soles_XC9Jmba.jpg" alt="Inner Soles">
            </a>
            <div class="caption">
                <h4 style="color: grey">Inner Soles</h4>
            </div>
        </div>

        <div class="item">
            <a href="{% url 'brands:Jordans' %}" style="text-decoration: none; cursor: grab;">
                <img class="img-fluid" src="media/shoes/Air_Jordan_3_infrared_23_0MBYHLM.jpg" alt="Air Jordan 3">
            </a>
            <div class="caption">
                <h4 style="color: grey">Air Jordan 3</h4>
            </div>
        </div>
    </div>
</div>

<!-- Scripts to support the Jquery Owl-carousels -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
<!--The responsiveness of the carousels -->
<script type="text/javascript">
    $('.owl-carousel').owlCarousel({
    loop: true,
    margin: 30,
    nav: false,
    autoplay: true,
    autoplayTimeout: 3000,
    margin: 30,
    autoplayHoverPause: true,
    dots: false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:4
        }
    }
})
</script>
<br><br><br><br>

<!-- SHOP TESTIMONIALS STYLIN[testimonial.css] static [testimonial.html]-->

<div class="container">
    <h3 class="display-5 text-center mt-5"><strong>What People are saying</strong></h3>
    <div class="row">
        <div class="col">
            <section class="testimonial_wrap col-12">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="slider">
                            <!-- testimonies--->
                                {% for testimony in shop_testimonies %}
                                    {% if testimony.approved %}
                                        <div class="item">
                                            <div class="inner">
                                                <div class="thumb">
                                                    {% if testimony.user.userprofile.profile_picture %}
                                                        <img src="{{ testimony.user.userprofile.profile_picture.url }}" class="img-fluid">
                                                    {% else %}
                                                        <img src="{% static 'default-profile-pic.png' %}" class="img-fluid">
                                                    {% endif %}
                                                </div>
                                                <div class="excert col-12">
                                                    <p>
                                                        {{ testimony.comment }}
                                                    </p>
                                                    <div class="info">
                                                        <p>
                                                            <i class="fa fa-quote-right"></i>
                                                            {% if testimony.user == request.user %}
                                                                <a href="javascript:void(0);" style="text-decoration: none;">You</a>
                                                            {% else %}
                                                                <a href="javascript:void(0);" style="text-decoration: none;">{{ testimony.user.username }}</a>
                                                            {% endif %}
                                                            <span>Top Gz customer</span>
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js" integrity="sha512-3gJwYpMe3QewGELv8k/BX9vcqhryRdzRMxVfq6ngyWXwo03GFEzjsUm8Q7RZcHPHksttq7/GFoxjCVUjkjvPdw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js" integrity="sha512-HGOnQO9+SP1V92SrtZfjqxxtLmVzqZpjFFekvzZVWoiASSQgSr4cw9Kqd2+l8Llp4Gm0G8GIFJ4ddwZilcdb8A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js" integrity="sha512-rMVwujtLz2JWFJvF9R8rlMcBQ4inAWaST5B3u4eUv7zA1B2FFc0X4f5i9YNbV0rFNTZjpXbzWDEerUdA1h/jw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="text/javascript">
    $('.slider').slick({
        slidesToshow: 1,
        slidesToScroll: 1,
        arrows: false,
        dots: true,
        loop: true,
        speed: 1500,
        autoplay: true,
        autoplaySpeed: 3000,
        infinite: true,
    });
</script>
<br><br><br>

<!--THE SHOP -->

<h3 class="display-5 text-center mt-5"><strong>Improve your footwear</strong></h3>
<br>
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6">
            <img class="img-fluid" src="{% static 'services.jpg' %}">
        </div>
        <div class="col-md-6 mt-3 mt-md-0">
            <h1 class="mb-4">Unleash Your Style Potential with Top Gz Shoe Shop</h1>
            <p style="font-size: larger;">
                Experience exceptional service, top-notch quality, and a wide selection of footwear for men, women, and children.
                Step into fashion-forward comfort and elevate your shoe game with us.
            </p>
            <div class="d-flex justify-content-center align-items-center mt-3">
                <a href="{% url 'servicesPage:services-page' %}" class="btn btn-outline-secondary btn-lg"><strong>Our Services</strong></a>
            </div>
        </div>
    </div>
</div>
<br><br>
<!-- ABOUT THE SHOP LINK -->
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <img class="img-thumbnail rounded img-fluid" style="object-fit: cover;" src="{% static 'intro-bg.jpg' %}" alt="Vans Slip-on custom.jpg">
        </div>
        <div class="col-md-6 mt-3 mt-md-0">
            <h1 class="mb-4">Your go-to destination for stylish and comfortable footwear</h1>
            <p style="font-size: larger;">
                At Top Gz Shoe Shop, we are committed to providing you with the best shoe shopping experience possible.
            </p>
            <div class="d-flex justify-content-center align-items-center mt-3">
                <a href="{% url 'introPage:about-page' %}" class="btn btn-outline-secondary btn-lg"><strong>LEARN MORE ABOUT US</strong></a>
            </div>
        </div>
    </div>
</div>
<br><br><br><br>
<!--THE TEAM LINK -->
<div class="container mt-5">
    <h3 class="display-5 text-center mb-4"><strong>Our Team</strong></h3>
    <blockquote class="blockquote text-center">
        <p>
            We are passionate about footwear and are ready to assist you in every step of your shoe-shopping journey.
            Meet the Top Gz Shoe Shop Team – a group of dedicated shoe enthusiasts committed to providing you with exceptional service.
        </p>
    </blockquote>
    <div class="row justify-content-center align-items-center">
        <div class="col-12 col-md-4 mb-4">
            <img class="img-circle team-img img-fluid" src="{% static 'team22.jpg' %}" alt="shoe">
        </div>
        <div class="col-12 col-md-4 mb-4">
            <img class="img-circle team-img img-fluid" src="{% static 'team1.jpg' %}" alt="shoe">
        </div>
        <div class="col-12 col-md-4 mb-4">
            <img class="img-circle team-img img-fluid" src="{% static 'team3.jpg' %}" alt="shoe">
        </div>
    </div>
    <div class="d-flex justify-content-center align-items-center mt-4">
        <a href="{% url 'introPage:team-page' %}" class="btn btn-outline-secondary btn-lg"><strong>MEET THE TEAM</strong></a>
    </div>
</div>
<br><br><br>
<!--FOOTER -->
{% include 'baseshop_footer.html' %}
</body>
</html>

the_shop/top_shop/templates/message_added_email.html
Hello, {{ name }}

You have a new message from your Top Gz website.

From: {{ first_name }}  {{ last_name }}
Email: {{ email }}
Message: {{ message }}

Regards,
Top Gz team.
topgz.ebby@gmail.com

the_shop/top_shop/templates/message_sent_email.html
Hello, {{ first_name }}

We have received your message " {{ message }} " and will get back to you soon.

Regards,
Top Gz team.
topgz.ebby@gmail.com