the_shop/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'


urlpatterns = [
    path('sign_up/', views.sign_up, name="sign_up"),
    path('check_email_to_log_in/', views.signup_redirect, name="redirect"),
    path('log_in/', views.log_in, name="log_in"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('profile_details/', views.profile_details, name="profile_details"),
    path('password_change/', views.password_change, name='password_change'),
    path('password_changed_check_email_to_log_in/', views.password_change_redirect, name="password_changed"),
    path('delete_profile_picture/', views.delete_profile_picture, name="delete_profile_picture"),
    path('log_out/', views.log_out, name="log_out"),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name="password_reset_complete")
]

the_shop/brands/urls.py
from django.urls import path
from . import views

app_name = 'brands'

urlpatterns = [
    path('Jordans/', views.jordans, name="Jordans"),
    path('Nikes/', views.nikes, name="Nikes"),
    path('Vans/', views.vans, name="Vans"),
    path('Yeezys/', views.yeezys, name="Yeezys"),
    path('Pradas/', views.pradas, name="Pradas"),
    path('Shoes Accessories/', views.shoes_accessories, name="Shoes Accessories"),
    path('Pumas/', views.pumas, name="Pumas"),
    path('Balenciagas/', views.balenciagas, name="Balenciagas"),
    path('Gucci/', views.gucci, name="Gucci"),
    path('Louis Vuitton/', views.louis_vuitton, name="Louis Vuitton"),
    path('Versace/', views.versace, name="Versace"),
    path('Addidas/', views.addidas, name="Addidas"),
    path('', views.catalogue, name="catalogue"),
    path('size-guide/', views.size_guide, name="size_guide")
]

the_shop/the_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('top_shop.urls')),
    path('shop_services/', include('shop_services.urls')),
    path('catalogue/', include('brands.urls')),
    path('account/', include('accounts.urls')),
    path('orders/', include('theorders.urls')),
    path('account/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

the_shop/accounts/models.py
from django.db import models

from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    profile_picture = models.ImageField(upload_to='user_profiles/', height_field='image_height', width_field='image_width', null=True, blank=True)
    image_height = models.PositiveIntegerField(blank=True, null=True)
    image_width = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return str(self.user)

the_shop/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django import forms
from .models import UserProfile


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    profile_pic = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'form-control'}))

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email address is already in use.")
        return email

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].validators.append(MinLengthValidator(4))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_pic')


class EditProfileForm(UserChangeForm):
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    profile_pic_change = forms.ImageField(required=False, widget=forms.ClearableFileInput(attrs={'class': 'form-control'}))

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if self.is_valid() and 'email' in self.changed_data:
            if User.objects.filter(email=email).exists():
                raise forms.ValidationError("This email address is already in use.")
        return email

    class Meta:
        model = UserProfile
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_pic_change')


class ChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))
    new_password1 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))
    new_password2 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type': 'password'}))

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

the_shop/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from .forms import SignUpForm, EditProfileForm, ChangePasswordForm
from .models import UserProfile
from django.core.files.storage import default_storage
from django.http import JsonResponse
from theorders.models import Order
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.conf import settings


def sign_up(request):
    if request.method == 'POST':
        sign_up_form = SignUpForm(request.POST, request.FILES)
        if sign_up_form.is_valid():
            email = sign_up_form.cleaned_data['email']
            first_name = sign_up_form.cleaned_data['first_name']
            last_name = sign_up_form.cleaned_data['last_name']
            username = sign_up_form.cleaned_data['username']
            user = sign_up_form.save()
            profile_picture = sign_up_form.cleaned_data['profile_pic']
            UserProfile.objects.create(user=user, profile_picture=profile_picture)

            template = render_to_string('signup_complete.html', {
                "first_name": first_name,
                "last_name": last_name,
                "username": username,
                "email": email
            })
            sent_email = EmailMessage(
                'Welcome to Top Gz',
                template,
                settings.EMAIL_HOST_USER,
                [email]
            )
            sent_email.fail_silently = False
            sent_email.send()

            return redirect('accounts:redirect')
    else:
        sign_up_form = SignUpForm()
    return render(request, 'sign-up.html', {"sign_up_form": sign_up_form})


def signup_redirect(request):
    return render(request, 'redirected.html')


def log_in(request):
    if request.method == 'POST':
        log_in_form = AuthenticationForm(data=request.POST)
        if log_in_form.is_valid():
            user = log_in_form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('introPage:home-page')
    else:
        log_in_form = AuthenticationForm()
    return render(request, 'log_in.html', {"log_in_form": log_in_form})


def edit_profile(request):
    customer = request.user
    order, created = Order.objects.get_or_create(user=customer, complete=False)
    if request.method == 'POST':
        edit_profile_form = EditProfileForm(request.POST, request.FILES, instance=request.user)
        if edit_profile_form.is_valid():
            user_profile = edit_profile_form.save()

            # Check if a new profile picture is provided
            if 'profile_pic_change' in request.FILES:
                profile_picture = edit_profile_form.cleaned_data['profile_pic_change']
                user_profile = UserProfile.objects.get(user=request.user)
                user_profile.profile_picture = profile_picture
                user_profile.save()

            user_profile.save()
            return redirect('accounts:profile_details')
    else:
        edit_profile_form = EditProfileForm(instance=request.user)
    return render(request, 'edit_profile.html', {'edit_profile_form': edit_profile_form, "order": order})


def password_change(request):
    customer = request.user
    order, created = Order.objects.get_or_create(user=customer, complete=False)
    if request.method == 'POST':
        edit_password_form = ChangePasswordForm(request.user, request.POST)
        if edit_password_form.is_valid():
            edit_password_form.save()

            template = render_to_string('password_changed_email.html', {
                "user": request.user.username,
                "name": request.user.first_name,
            })
            email = EmailMessage(
                'Your password has been changed successfully',
                template,
                settings.EMAIL_HOST_USER,
                [request.user.email]
            )
            email.fail_silently = False
            email.send()
            return redirect('accounts:password_changed')
    else:
        edit_password_form = ChangePasswordForm(request.user)
    return render(request, 'change_password.html', {"edit_password_form": edit_password_form, "order": order})


def password_change_redirect(request):
    return render(request, 'password_change_redirect.html')


def profile_details(request):
    customer = request.user
    order, created = Order.objects.get_or_create(user=customer, complete=False)
    return render(request, 'profile_details.html', {"order": order})


def delete_profile_picture(request):
    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        user_profile = UserProfile.objects.get(user_id=user_id)

        # Delete the profile picture file from storage
        if user_profile.profile_picture:
            default_storage.delete(user_profile.profile_picture.path)

        # Set the profile picture field to None
        user_profile.profile_picture = None
        user_profile.save()

        return JsonResponse({'message': 'Profile picture deleted.'})
    return JsonResponse({'error': 'Invalid request method.'})


def log_out(request):
    if request.method == 'POST':
        logout(request)
        return redirect('accounts:log_in')
    return

the_shop/accounts/templates/change_password.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CHANGE PASSWORD</title>
    <link rel="shortcut icon" href="{% static 'logo.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/page-header.css' %}">
</head>
<body>
{% include 'bootstrap.html' %}
{% include 'backToTop.html' %} <!--Back to Top button -->
<br><br>
<div class="custom-container">
    <h3 class="display-3">
        <strong>CHANGE YOUR PASSWORD</strong><!-- page-header.css for custom container styling -->
    </h3>
</div>
<br><br>
<form class="site-form" action="{% url 'accounts:password_change' %}" method="post">
    {% csrf_token %}
    <em style="font-weight: bold;">Old Password</em><br>
    {{ edit_password_form.old_password }} <br>
    <em style="font-weight: bold;">New Password</em><br>
    {{ edit_password_form.new_password1 }} <br>
    <em style="font-weight: bold;">Confirm New Password</em><br>
    {{ edit_password_form.new_password2 }} <br>
    <ul>
        <li>Your password can’t be too similar to your other personal information.</li>
        <li>Your password must contain at least 8 characters.</li>
        <li>Your password can’t be a commonly used password.</li>
        <li>Your password can’t be entirely numeric.</li>
    </ul>
    <br>
    <input type="submit" class="btn btn-outline-secondary" value="change my password">
</form>
<br><br>
{% include 'baseshop_footer.html' %}
</body>
</html>

the_shop/accounts/templates/edit_profile.html
{% load static %}
<!--suppress XmlDuplicatedId -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>EDIT PROFILE</title>
    <link rel="shortcut icon" href="{% static 'logo.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/page-header.css' %}">
</head>
<body>
{% include 'bootstrap.html' %}
{% include 'backToTop.html' %} <!--Back to Top button -->
<br><br>
<div class="custom-container">
    <h3 class="display-3">
        <strong>EDIT PROFILE</strong><!-- page-header.css for custom container styling -->
    </h3>
</div>
<br><br>
<div class="container">
    <form class="site-form" action="{% url 'accounts:edit_profile' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <br>
        <div class="d-flex justify-content-center align-items-center">
                {% if user.userprofile.profile_picture %}
            <a href="{{ user.userprofile.profile_picture.url }}">
                    <img id="profile-image" class="rounded-circle" src="{{ user.userprofile.profile_picture.url }}" style="object-fit: cover; width: 200px; height: 200px;">
            </a>
            <a href="{% url 'accounts:delete_profile_picture' %}" id="delete-profile-picture" style="text-decoration: none; color: black;">
                    <span class="delete-icon" style="font-size: 24px;">&#128686;</span>
            </a>
                {% else %}
                    <img id="profile-image" class="rounded-circle" src="{% static 'default-profile-pic.png' %}" style="object-fit: cover; width: 200px; height: 200px;">
                {% endif %}
        </div>
        <input type="file" id="profile-picture-input" style="display: none;" accept="image/*">
        <br>
        <div class="form-group">
            <em style="font-weight: bold;">Username:</em>
            <br>
            <em>Required:<small style="font-weight: bold"> 150 characters or fewer. Letters, digits and @/./+/-/_ only<small>...</small><em style="font-weight: bold; font-size: 20px;">no spacing</em></small> </em>
            {{ edit_profile_form.username }}
        </div>
        <div class="form-group">
            <em style="font-weight: bold;">First Name:</em>
            <br>
            {{ edit_profile_form.first_name }}
        </div>
        <div class="form-group">
            <em style="font-weight: bold;">Last Name:</em>
            <br>
            {{ edit_profile_form.last_name }}
        </div>
        <div class="form-group">
            <em style="font-weight: bold;">Email:</em>
            <br>
            {{ edit_profile_form.email }}
        </div>
        <div class="form-group">
            <em style="font-weight: bold;">Profile picture:</em>
            <br>
            {{ edit_profile_form.profile_pic_change }}
        </div>
        <small style="color: red;">{{ edit_profile_form.errors }}</small>
        <em><small style="font-weight: bold;">update profile</small> to display new profile photo <small style="font-weight: bold;">if changed</small> or <small style="font-weight: bold;">removed</small></em><br><br>
        <input type="submit" class="btn btn-outline-secondary" value="update profile">
    </form>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
  $(document).ready(function() {
    // Add a click event listener to the delete icon
    $('#delete-profile-picture').click(function(e) {
      e.preventDefault();

      // Perform an AJAX request to delete the profile picture
      $.ajax({
        url: '{% url 'accounts:delete_profile_picture' %}',
        method: 'POST',
        data: {
          'user_id': '{{ user.id }}',
          'csrfmiddlewaretoken': '{{ csrf_token }}'
        },
        success: function(response) {
          // Replace the profile picture with the default image
          $('#profile-image').attr('src', '{% static 'default-profile-pic.png' %}');
        },
        error: function(xhr, status, error) {
          // Handle the error if the deletion fails
          console.log(error);
        }
      });
    });
  });
</script>
<br><br>
{% include 'baseshop_footer.html' %}
</body>
</html>

the_shop/accounts/templates/log_in.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LOG IN</title>
    <link rel="shortcut icon" href="{% static 'logo.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/page-header.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
{% include 'bootstrap.html' %}
{% include 'backToTop.html' %} <!--Back to Top button -->
<br><br>
<div class="custom-container">
    <h3 class="display-3">
        <strong>LOG IN</strong><!-- page-header.css for custom container styling -->
    </h3>
    <em style="color: black;">
        Don't have an account?...<a style="text-decoration: none;" href="{% url 'accounts:sign_up' %}">Sign Up</a>
    </em>
</div>
<br><br>


<form class="site-form" action="{% url 'accounts:log_in' %}" method="post">
    {% csrf_token %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-3">
                <div class="form-group">
                    <label style="font-weight: bold;">Username</label><br>
                    Required: <small style="font-weight: bold; font-size: 20px;">no spacing</small><br>
                    {{ log_in_form.username }}
                </div>
                <div class="form-group">
                    <br><label>Password</label><br>
                    {{ log_in_form.password }}
                </div>
                <small style="color: red;">{{ log_in_form.errors }}</small>
                {% if request.GET.next %}
                    <br><input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
                <br><input type="submit" class="btn btn-outline-secondary" value="log in">
            </div>
        </div>
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-md-6 text-center">
              <em><a href="{% url 'accounts:password_reset' %}" style="text-decoration: none; margin-left: 70px;">Forgot your password??</a></em>
            </div>
          </div>
        </div>
    </div>
</form>
<br><br>
{% include 'baseshop_footer.html' %}
</body>
</html>

the_shop/accounts/templates/order_email.html
Dear {{ name }},
Thank you for shopping at Top Gz! Your order {{ order_id }} has been successfully confirmed.
You ordered for:
{% for item in items %}
        {{ item.quantity }} product[s] of {{ item.product.shoe_name }} at ${{ item.product.shoe_price }} each
{% endfor %}
Number of ordered products: {{ total_products }}
Total: ${{ total }}
Mode of Pay: To be paid on delivery

Your order will be packaged and shipped as soon as possible. Once the item(s) is out for delivery or available for pick-up you will receive a notification from us.
Check the orders progress and order details here https://topgz-ebby.up.railway.app/orders/my_orders/

Thank you for shopping at Top Gz!

Please note:
        - If you ordered for multiple items, you may receive them on different days. We want to make each item available to you as soon as possible after receiving it.

Happy Shopping!!
Warm Regards,
Top Gz team.

Got any questions??
topgz.ebby@gmail.com
https://www.linkedin.com/in/zebbylion-njau/
https://wa.me/+254773253606

Follow Top Gz socials to get notified on the latest trends available:
https://www.linkedin.com/in/zebbylion-njau/
https://twitter.com/zebby_G
https://github.com/zebbyG/
https://medium.com/@ZebbyG

the_shop/accounts/templates/password_change_redirect.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PASSWORD RESET DONE</title>
    <link rel="shortcut icon" href="{% static 'logo.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/page-header.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body style="background-color: #1a1a1a;">
<br><br>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-3">
            <div class="alert alert-info">
                <em>
                    <b>Password changed successfully</b><br><br>
                    An Email has been sent to {{ email }} with a link to log in
                </em><br><br>
                <small>If you don’t receive an email, please make sure you registered with a valid email address</small>
            </div>
        </div>
    </div>
</div>
</body>
</html>

the_shop/accounts/templates/password_changed_email.html
Dear {{ name }},

Your account password has been successfully changed.

Log into your account here https://topgz-ebby.up.railway.app/account/log_in/

Your username incase you've forgotten:
        {{ user }}


Place an order at https://topgz-ebby.up.railway.app/catalogue/

Happy Shopping!!
Warm Regards,
Top Gz team.

Rate Us!!
Leave a comment at https://topgz-ebby.up.railway.app/orders/leave_a_comment/ and will be posted on our website

Have any questions??
topgz.ebby@gmail.com
https://www.linkedin.com/in/zebbylion-njau/
https://wa.me/+254773253606

Follow Top Gz socials to get notified on the latest trends available:
https://www.linkedin.com/in/zebbylion-njau/
https://twitter.com/zebby_G
https://github.com/zebbyG/
https://medium.com/@ZebbyG


THIS EMAIL IS AUTO-GENERATED AND YOU SHOULD NOT REPLY

the_shop/accounts/templates/password_reset.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PASSWORD RESET</title>
    <link rel="shortcut icon" href="{% static 'logo.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/page-header.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
{% include 'bootstrap.html' %}
{% include 'backToTop.html' %} <!--Back to Top button -->
<br><br>
<div class="custom-container">
    <h3 class="display-3">
        <strong>PASSWORD REQUEST</strong><!-- page-header.css for custom container styling -->
    </h3>
    <em style="color: black;">
        To reset your password...Enter a<b style="text-decoration: none;"> valid</b> email address and a mail will be sent with instructions
    </em>
</div>
<br><br>


<form class="site-form" action="{% url 'accounts:password_reset' %}" method="post">
    {% csrf_token %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-3">
                <div class="form-group">
<!--                    <label style="font-weight: bold;">Username</label><br>-->
<!--                    Required: <small style="font-weight: bold; font-size: 20px;">no spacing</small><br>-->
                    {{ form }}
                </div>
                <br><input type="submit" class="btn btn-outline-secondary" value="Request password reset">
            </div>
        </div>
    </div>
</form>
{% include 'baseshop_footer.html' %}
</body>
</html>

the_shop/accounts/templates/profile_details.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PROFILE DETAILS</title>
    <link rel="stylesheet" href="{% static 'css/page-header.css' %}">
    <link rel="shortcut icon" href="{% static 'logo.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css">
</head>
<body>
{% include 'bootstrap.html' %}
{% include 'backToTop.html' %} <!--Back to Top button -->
<br><br>
<div class="custom-container">
    <h3 class="display-3">
        <strong>{{ request.user }} details</strong><!-- page-header.css for custom container styling -->
    </h3>
</div>
<br><br>

<div class="container">
    {% if user.userprofile.profile_picture %}
        <div class="d-flex justify-content-center">
            <a href="{{ user.userprofile.profile_picture.url }}" style="text-decoration: none;">
                <img class="rounded-circle" src="{{ user.userprofile.profile_picture.url }}" style="object-fit: cover; width: 200px; height: 200px;">
                <small class="btn btn-dark">view</small>
            </a>
        </div>
    {% else %}
        <div class="d-flex justify-content-center">
            <img class="rounded-circle" src="{% static 'default-profile-pic.png' %}" style="object-fit: cover; width: 200px; height: 200px;">
        </div>
    {% endif %}
</div>
<br><br>
<div class="container">
    <table class="table table-hover square-table" style="width: 100%;">
        <tbody style="background-color: whitesmoke;">
            <tr>
                <td style="font-weight: bold;"><b>First Name</b></td>
                <td>{{ request.user.first_name }}</td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Last Name</td>
                <td>{{ request.user.last_name }}</td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Email</td>
                <td>{{ request.user.email }}</td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Username</td>
                <td>{{ request.user.username }}</td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Date Joined</td>
                <td>{{ request.user.date_joined }}</td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Last Log in</td>
                <td>{{ request.user.last_login }}</td>
            </tr>
        </tbody>
    </table>
</div>
<br>
<div class="container">
    <em class="d-flex justify-content-center"><a href="{% url 'accounts:edit_profile' %}" style="text-decoration: none;">edit your profile</a></em>
</div>
<br><br>
{% include 'baseshop_footer.html' %}
</body>
</html>

the_shop/accounts/templates/sign-up.html
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>SIGN-UP</title>
    <link rel="shortcut icon" href="{% static 'logo.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/page-header.css' %}">
</head>
<body>
{% include 'bootstrap.html' %}
{% include 'backToTop.html' %} <!--Back to Top button -->
<br><br>
<div class="custom-container">
    <h3 class="display-3">
        <strong>SIGN UP</strong><!-- page-header.css for custom container styling -->
    </h3>
    <em style="color: black;">
        Already have an account?... <a style="text-decoration: none;" href="{% url 'accounts:log_in' %}">Log in</a>
    </em>
</div>
<br><br>
<form class="site-form" action="{% url 'accounts:sign_up' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <em style="font-weight: bold;">Username:</em><br>
    <em>Required:<small style="font-weight: bold"> 4 - 150 characters. Letters, digits and @/./+/-/_ only<small>...</small><em style="font-weight: bold; font-size: 20px;">no spacing</em></small></em><br>
    {{ sign_up_form.username }}<br>
    <em style="font-weight: bold;">First name:</em><br>
    {{ sign_up_form.first_name }}
    <em style="font-weight: bold;">Last name:</em><br>
    {{ sign_up_form.last_name }}
    <em style="font-weight: bold;">Email:</em><br>
    {{ sign_up_form.email }}
    <em style="font-weight: bold;">Profile picture:</em><small> (optional)</small><br>
    {{ sign_up_form.profile_pic }}
    <em style="font-weight: bold;">Password:</em><br>
    {{ sign_up_form.password1 }}
    <small style="color: red;">{{ sign_up_form.errors }}</small>
    <ul>
        <li>Your password can’t be too similar to your other personal information.</li>
        <li>Your password must contain at least 8 characters.</li>
        <li>Your password can’t be a commonly used password.</li>
        <li>Your password can’t be entirely numeric.</li>
    </ul>
    <em style="font-weight: bold;">Password confirmation:</em><br>
    {{ sign_up_form.password2 }}
    <br><em>Enter the same password as <small style="font-weight: bold;"> before </small>for verification</em><br>
    <br><em>By clicking <small style="font-weight: bold;"> sign_up </small>you have agreed to Top Gz <small style="font-weight: bold;"> terms & conditions </small></em><br><br>
    <input type="submit" class="btn btn-outline-secondary" value="signup">
</form>
<br><br>
{% include 'baseshop_footer.html' %}
</body>
</html>