the_shop/brands/urls.py
from django.urls import path
from . import views

app_name = 'brands'

urlpatterns = [
    path('Jordans/', views.jordans, name="Jordans"),
    path('Nikes/', views.nikes, name="Nikes"),
    path('Vans/', views.vans, name="Vans"),
    path('Yeezys/', views.yeezys, name="Yeezys"),
    path('Pradas/', views.pradas, name="Pradas"),
    path('Shoes Accessories/', views.shoes_accessories, name="Shoes Accessories"),
    path('Pumas/', views.pumas, name="Pumas"),
    path('Balenciagas/', views.balenciagas, name="Balenciagas"),
    path('Gucci/', views.gucci, name="Gucci"),
    path('Louis Vuitton/', views.louis_vuitton, name="Louis Vuitton"),
    path('Versace/', views.versace, name="Versace"),
    path('Addidas/', views.addidas, name="Addidas"),
    path('', views.catalogue, name="catalogue"),
    path('size-guide/', views.size_guide, name="size_guide")
]

the_shop/the_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('top_shop.urls')),
    path('shop_services/', include('shop_services.urls')),
    path('catalogue/', include('brands.urls')),
    path('account/', include('accounts.urls')),
    path('orders/', include('theorders.urls')),
    path('account/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

the_shop/theorders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('add_to_cart/', views.add_to_cart, name="add_to_cart"),
    path('checkout/', views.check_out, name="checkout"),
    path('update_item/', views.update_item, name="update_item"),
    path('process_order/', views.process_order, name="process_order"),
    path('my_orders/', views.complete_orders, name="my_orders"),
    path('order_completed/', views.order_complete, name="order_completed"),
    path('leave_a_comment/', views.leave_comment, name="leave_a_comment")
    # path('delete_order/', views.delete_order, name='delete_order')
]

the_shop/theorders/models.py
from django.db import models
from django.contrib.auth.models import User
from brands.models import Product
import random
import string


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now=True)
    complete = models.BooleanField(default=False)
    delivered = models.BooleanField(default=False)
    date_delivered = models.DateTimeField(null=True, blank=True, auto_now=True)
    paid = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=250, null=True)

    def __str__(self):
        return f'Order for {self.user} complete: {self.complete}'

    def save(self, *args, **kwargs):
        if not self.transaction_id:
            self.transaction_id = self.generate_transaction_id(self.user_id)
        return super().save(*args, **kwargs)

    @staticmethod
    def generate_transaction_id(user_id):
        user = User.objects.get(id=user_id) if user_id else None
        username = user.username if user else ''  # Get the username if the user exists
        max_length = max(8, min(12, 12 - len(username)))  # Calculate the maximum length for the random part

        random_part = ''.join(random.choices(string.ascii_letters + string.digits, k=max_length))
        transaction_id = random_part + "-" + username
        return transaction_id

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.quantity}-{self.product}  => {self.order}'

    @property
    def get_total(self):
        total_price = self.product.shoe_price * self.quantity
        return total_price


class ShippingAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    country = models.CharField(max_length=250, null=True, default="Kenya")
    address = models.CharField(max_length=250, null=True)
    city = models.CharField(max_length=250, null=True)
    state = models.CharField(max_length=250, null=True)
    zip_code = models.CharField(max_length=250, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.order}  => to be delivered to {self.city} {self.country}'


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    comment = models.CharField(max_length=500)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return f'Comment from {self.user.username}  approved: {self.approved}'

the_shop/theorders/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    comment = forms.CharField(max_length=500, widget=forms.Textarea(attrs={'class': 'form-control'}))

    class Meta:
        model = Comment
        fields = ['comment']

the_shop/theorders/views.py
import time

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
import json
from django.http import JsonResponse
from .models import *
from brands.models import Product, Size
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string
from .forms import CommentForm


@login_required(login_url='accounts:log_in')
def add_to_cart(request):
    customer = request.user
    order, created = Order.objects.get_or_create(user=customer, complete=False)
    items = order.orderitem_set.all()
    size = Size.objects.all().order_by('-time_added')
    return render(request, 'add_to_cart.html', {
        "items": items,
        "order": order,
        "size": size
    })


@login_required(login_url='accounts:log_in')
def check_out(request):
    customer = request.user
    order, created = Order.objects.get_or_create(user=customer, complete=False)
    items = order.orderitem_set.all()
    shipping_address = ShippingAddress.objects.filter(user=customer).order_by('-date_added').first()
    return render(request, 'check_out.html', {
        "items": items,
        "order": order,
        "shipping_address": shipping_address,
    })


@login_required(login_url='accounts:log_in')
def update_item(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']

    print("ProductId:", productId)
    print("Action:", action)

    customer = request.user
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(user=customer, complete=False)
    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == 'add':
        orderItem.quantity = orderItem.quantity + 1
    elif action == 'remove':
        orderItem.quantity = orderItem.quantity - 1

    orderItem.save()

    if orderItem.quantity < 1:
        orderItem.delete()

    return JsonResponse('item added successfully', safe=False)


@login_required(login_url='accounts:log_in')
def process_order(request):
    data = json.loads(request.body)
    customer = request.user
    order, created = Order.objects.get_or_create(user=customer, complete=False)
    total = float(data['form']['total'])

    if total == float(order.get_cart_total):
        order.complete = True
    order.save()

    ShippingAddress.objects.create(
        user=customer,
        order=order,
        address=data['shipping']['address'],
        city=data['shipping']['city'],
        state=data['shipping']['state'],
        zip_code=data['shipping']['zipcode'],
        country=data['shipping']['country']
    )
    template = render_to_string('order_email.html', {
        'name': request.user.username,
        'order_id': order.transaction_id,
        'items': order.orderitem_set.all,
        'total': order.get_cart_total,
        'total_products': order.get_cart_items,
    })

    email = EmailMessage(
        f'Your TOP Gz Order has been confirmed',
        template,
        settings.EMAIL_HOST_USER,
        [request.user.email]
    )
    email.fail_silently = False
    email.send()
    return JsonResponse('Payment completed successfully', safe=False)


@login_required(login_url='accounts:log_in')
def complete_orders(request):
    customer = request.user
    order, created = Order.objects.get_or_create(user=customer, complete=False)
    orders_completed = Order.objects.filter(user=customer, complete=True).order_by('-date_ordered')
    shipping_addresses = ShippingAddress.objects.filter(order__in=orders_completed)

    return render(request, 'complete_orders.html', {
        "orders_completed": orders_completed,
        "order": order,
        "shipping_addresses": shipping_addresses,
    })


@login_required(login_url='accounts:log_in')
def order_complete(request):
    customer = request.user
    order, completed = Order.objects.get_or_create(user=customer, complete=False)
    return render(request, 'order_completed.html', {
        "order": order
    })


@login_required(login_url='accounts:log_in')
def leave_comment(request):
    customer = request.user
    order, completed = Order.objects.get_or_create(user=customer, complete=False)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.save()
            template = render_to_string('comment_approval.html', {
                "comment": comment.comment,
                "name": request.user.username
            })
            email = EmailMessage(
                'Your comment has been received and is awaiting for approval',
                template,
                settings.EMAIL_HOST_USER,
                [request.user.email]
            )
            email.fail_silently = False
            email.send()
            time.sleep(2.5)
            return redirect('introPage:home-page')
    else:
        form = CommentForm()

    return render(request, 'comment.html', {"form": form, "order": order})
# def delete_order(request):
#     if request.method == 'POST':
#         order_id = request.POST.get('order_id')
#         order = Order.objects.get(id=order_id)
#         order.delete()
#         return JsonResponse({'message': 'Order deleted successfully.'})
#     return

the_shop/theorders/templates/add_to_cart.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ADD-TO-CART</title>
	<link rel="shortcut icon" href="{% static 'logo.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/page-header.css' %}">
</head>
<body>
{% if user.is_authenticated %}
    <script src="{% static 'js/csrf_token.js' %}"></script>
{% endif %}

{% include 'bootstrap.html' %}
{% include 'backToTop.html' %} <!--Back to Top button -->
<br><br>
<div class="custom-container">
    <h3 class="display-3">
        <strong>ADD TO CART</strong>
    </h3>
</div>
<br><br>
<div class="row">
	<div class="col-lg-12">
	{% if order.get_cart_items %}
		<a style="color: grey;" class="btn btn-outline-dark" href="{% url 'brands:catalogue' %}">&#x2190; <b>Continue Shopping</b></a>
		<br>
		<br>
			<table class="table">
				<tr>
					<th><h5>Items: <strong>{{ order.get_cart_items }}</strong></h5></th>
					<th><h5>Total:<strong> ${{ order.get_cart_total }}</strong></h5></th>
					<th>
						<a style="float:right; margin: 15px; margin-right: 40px;" class="btn btn-outline-success" href="{% url 'orders:checkout' %}">Checkout</a>
					</th>
				</tr>
			</table>
	{% else %}
		<div class="row">
		<div class="col-lg-12">
			<a style="color: grey;" class="btn btn-outline-dark" href="{% url 'brands:catalogue' %}">&#x2190; <b>Start Shopping</b></a>
		</div>
		</div>

		<p><strong class="h1" style="margin-left: 550px;">No items added</strong></p>
		<img style="width: 400px; height: 400px; object-fit: cover; margin-left: 470px;" id="cart-icon" src="{% static 'cart.png' %}">
		<small class="lead" style="margin-left: 530px;">Items added to cart will appear here</small><hr>
	{% endif %}
		</div>
	<br>
	{% if order.get_cart_items %}
		<div class="cart-row">
			<div style="flex:2"></div>
			<div style="flex:2"><strong>Item</strong></div>
			<div style="flex:2"><strong>Color</strong></div>
			<div style="flex:3"><strong>Size</strong></div>
			<div style="flex:1"><strong style="margin-right: 100px;">Price</strong></div>
			<div style="flex:1"><strong>Quantity</strong></div>
			<div style="flex:1"><strong>Total</strong></div>
		</div>
	{% for item in items %}
		<div class="cart-row">
			<div style="flex:2"><img class="row-image" src="{{ item.product.shoe_image.url }}" style="width: 100px; height: 80px; object-fit: cover;"></div>
			<div style="flex:2"><p>{{ item.product.shoe_name }}</p></div>
			{% for color in item.product.shoe_color_available.all %}
			<div style="flex:2"><p>{{ color.color_name }}</p></div>
			{% endfor %}
			<div style="flex:3">
				<div>
					<p>Size saved</p>
<!--					<label for="size-filter"></label>-->
<!--					<select id="size-filter">-->
<!--						<option value="all">Select Size</option>-->
<!--						{% for sizes in size %}-->
<!--						<option value="{{ sizes.size_number }}">{{ sizes.size_number }}</option>-->
<!--						{% endfor %}-->
<!--					</select>-->
				</div>
			</div>
			<div style="flex: 1; margin-right: 40px;"><p>${{ item.product.shoe_price }}</p></div>
			<div style="flex:1">
				<p class="quantity">x{{ item.quantity }}</p>
				<div class="quantity">
					<img data-product="{{ item.product.id }}" data-action="add" class="chg-quantity update-cart" src="{% static 'arrow-up.png' %}">

					<img data-product="{{ item.product.id }}" data-action="remove" class="chg-quantity update-cart" src="{% static 'arrow-down.png' %}">
				</div>
			</div>
			<div style="flex:1"><p>${{ item.get_total }}</p></div>
		</div>
	{% endfor %}
	{% endif %}
</div>
<script src="/assets/js/cart.js"></script>
<br><br><br>
{% include 'baseshop_footer.html' %}
</body>
</html>

the_shop/theorders/templates/check_out.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CHECKOUT</title>
	<link rel="shortcut icon" href="{% static 'logo.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/page-header.css' %}">
</head>
<body>
{% if user.is_authenticated %}
    <script src="{% static 'js/csrf_token.js' %}"></script>
{% endif %}

{% include 'bootstrap.html' %}
{% include 'backToTop.html' %} <!--Back to Top button -->
<br><br>
<div class="custom-container">
    <h3 class="display-3">
        <strong>CHECKOUT</strong><!-- page-header.css for custom container styling -->
    </h3>
</div>
<br><br>

<div class="row d-flex">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper" style="background-color: darkgray;">
				<form id="form">
					<!-- <div id="user-info">
						<div class="form-field hidden">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field hidden">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div> -->

					{% if shipping_address %}
						<div id="shipping-info">
							<hr>
							<p>Shipping Information:</p>
							<hr>
							<div class="form-field">
								<input class="form-control" type="text" name="country" placeholder="country.." value="{{ shipping_address.country }}">
							</div>
							<div class="form-field">
								<input class="form-control" type="text" name="city" placeholder="City.." value="{{ shipping_address.city }}">
							</div>
							<div class="form-field">
								<input class="form-control" type="text" name="state" placeholder="State.." value="{{ shipping_address.state }}">
							</div>
							<div class="form-field">
								<input class="form-control" type="text" name="zipcode" placeholder="Zip code.." value="{{ shipping_address.zip_code }}">
							</div>
							<div class="form-field">
								<input class="form-control" type="text" name="address" placeholder="Address.."  value="{{ shipping_address.address }}">
							</div>
						</div>
					<hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
					{% else %}
						<div id="shipping-infoo">
							<hr>
							<p style="color: grey;">Shipping Information:</p>
							<hr>
							<div class="form-field">
								<input class="form-control" type="text" name="country" placeholder="Country..">
							</div>
							<div class="form-field">
								<input class="form-control" type="text" name="city" placeholder="City..">
							</div>
							<div class="form-field">
								<input class="form-control" type="text" name="state" placeholder="State..">
							</div>
							<div class="form-field">
								<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
							</div>
							<div class="form-field">
								<input class="form-control" type="text" name="address" placeholder="Address..">
							</div>
						</div>

					<hr>
					<input id="form-button" class="btn btn-success btn-block hidden" type="submit" value="Continue">
					{% endif %}
				</form>
			</div>

			<br>
			<div class="box-element hidden" id="payment-info" style="background-color: darkgray;">
				<b style="color: grey;">Free Shipping and deliveries for your first 3 orders</b><br><br>
				<small style="color: grey;">Payment options:</small><br><br>
				<div class="d-grid gap-3">
					<p id="liveToastBtn">
						<button class="btn btn-outline-dark btn-lg" id="make-payment" style="width: 100%;">Pay on delivery</button>
					</p>
					<div style="position: fixed; bottom: 50%; right: 0; transform: translate(0, 50%); color: grey;" class="toast-container p-3">
						<div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="2500">
							<div class="toast-header">
								{% if user.userprofile.profile_picture %}
									<img src="{{ user.userprofile.profile_picture.url }}" class="rounded me-2" style="width: 50px; height: 70px; object-fit: cover;">
								{% else %}
									<h5> {{ request.user.username }}</h5>
								{% endif %}
								<a class="me-auto" href="{% url 'orders:my_orders' %}" style="text-decoration: none;"><b>View Complete Orders</b></a>
								<div class="spinner-grow spinner-grow-sm" role="status">
								  <span class="visually-hidden"></span>
								</div>
								<button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
							</div>
							<div class="toast-body">
								<p class="lead">
									Order Was placed successfully, check <a class="me-auto" href="{% url 'orders:my_orders' %}" style="text-decoration: none;"><b>My Orders</b></a> to see order details
								</p>
							</div>
						</div>
					</div>
				</div>
				<small style="color: grey;">Coming Soon:</small><br><br>
					<div id="paypal-button-container" style="pointer-events: none;"></div>
			</div>

		</div>

		<div class="col-lg-6">
			<div class="box-element" style="background-color: darkgray;">
				<a  class="btn btn-outline-dark" href="{% url 'orders:add_to_cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
				<hr>
				{% for item in items %}
				<div class="cart-row" style="color: black;">
					<div style="flex:2"><img class="row-image" src="{{ item.product.shoe_image.url }}"></div>
					<div style="flex:2"><p>{{ item.product.shoe_name }}</p></div>
					<div style="flex:1"><p>${{ item.product.shoe_price }}</p></div>
					<div style="flex:1"><p><b>x{{ item.quantity }}</b></p></div>
				</div>
				{% endfor %}
				<h5>Items:    {{ order.get_cart_items }}</h5>
				<h5>Total:    ${{ order.get_cart_total }}</h5>
			</div>
		</div>
	</div>
<script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>

<script>
	// Render the PayPal button into #paypal-button-container
	paypal.Buttons({

		// Call your server to set up the transaction
		createOrder: function(data, actions) {
			return actions.order.create({
				purchase_units: [{
					amount: {
						value: '0.01'
					}
				}]
			});
		},

		// FINALIZE THE TRANSACTION
		onApprove: function(data, actions) {
			return actions.order.capture().then(function(details) {
				// show success message to buyer
				alert('Transaction completed by' + details.payer.name.given_name + '!')
			});
		}

	}).render('#paypal-button-container');
 </script>

<script type="text/javascript">
	var form = document.getElementById('form')
	var total = '{{order.get_cart_total}}'
	var formButton = document.getElementById('form-button');
	var formFields = form.querySelectorAll('input[name]:not([type="submit"])');

	// Check if all form fields are filled
	function validateForm() {
		var isFormValid = true;
		formFields.forEach(function(field) {
			if (field.value.trim() === '') {
				isFormValid = false;
			}
		});
		return isFormValid;
	}

	// Show or hide the form button based on form validation status
	function toggleFormButton() {
		if (validateForm()) {
			formButton.classList.remove('hidden');
		} else {
			formButton.classList.add('hidden');
		}
	}

	// Listen for changes in form fields
	formFields.forEach(function(field) {
		field.addEventListener('input', toggleFormButton);
	});

	form.addEventListener('submit', function(e){
		e.preventDefault()
		console.log('form submitted successfully')
		document.getElementById('form-button').classList.add('hidden')
		document.getElementById('payment-info').classList.remove('hidden')
	})


	document.getElementById('make-payment').addEventListener('click', function(e){
		submitFormData()
	})

	function submitFormData(){
		console.log('Payment button clicked')

		var userFormData = {
			"total": total,
		}

		var shippingInfo = {
			"address": null,
			"city": null,
			"state": null,
			"zipcode": null,
			"country": null,
		}

		shippingInfo.address = form.address.value
		shippingInfo.city = form.city.value
		shippingInfo.state = form.state.value
		shippingInfo.zipcode = form.zipcode.value
		shippingInfo.country = form.country.value

		var url = '/orders/process_order/'

		fetch(url, {
			method: 'POST',
			headers: {
				'Content-Type':'application/json',
            	'X-CSRFToken': csrftoken,
			},
			body:JSON.stringify({
				"form": userFormData,
				"shipping": shippingInfo
			})
		})
		.then((response) => response.json())

		.then((data) => {
			console.log('Success', data);
			setTimeout(function() {
				window.location.href = "{% url 'orders:leave_a_comment' %}";
			}, 500);
		})
	}
</script>
<script src="{% static 'js/live_toast.js' %}"></script>
<br><br><br><hr>
{% include 'baseshop_footer.html' %}
</body>
</html>

the_shop/theorders/templates/comment.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LEAVE US A COMMENT</title>
    <link rel="stylesheet" href="{% static 'css/page-header.css' %}">
    <link rel="shortcut icon" href="{% static 'logo.ico' %}" type="image/x-icon">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<!-- Include Bootstrap JS and jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

{% include 'bootstrap.html' %}
{% include 'backToTop.html' %} <!--Back to Top button -->
<br><br>
<div class="container">
    <div class="custom-container">
        <h3 class="display-3">
            <strong>Leave us a comment</strong><!-- page-header.css for custom container styling -->
        </h3>
    </div>
</div>
<br>
<div style="position: relative;">
    <div class="position-fixed">
        <div style="margin-left: 500px;" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
                {% if user.userprofile.profile_picture %}
                    <img src="{{ user.userprofile.profile_picture.url }}" class="rounded me-2" style="width: 50px; height: 70px; object-fit: cover;">
                {% else %}
                    <h5> {{ request.user.username }}</h5>
                {% endif %}
                <strong class="me-auto"><a href="{% url 'orders:my_orders' %}" style="text-decoration: none; color: grey;">Order confirmed</a></strong>
                <small>...</small>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body" style="color: black;">
                Order was placed successfully. Check email<br>
            </div>
        </div>
    </div>
</div>
<form class="site-form" action="{% url 'orders:leave_a_comment' %}" method="post">
    {% csrf_token %}
    <em style="font-weight: bold;">Comment (<small>Tell us about your shopping experience with Top Gz</small>)</em><br>
    {{ form.comment }}
    <br>
    <input type="submit" class="btn btn-outline-secondary" value="Comment" id="liveToastBtn">
</form>
<div class="d-grid gap-3">
    <div style="position: fixed; bottom: 50%; right: 0; transform: translate(0, 50%); color: grey;" class="toast-container p-3">
        <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="4500">
            <div class="toast-header">
                <b>Posting comment</b>
                <div class="spinner-grow spinner-grow-sm" role="status">
                    <span class="visually-hidden"></span>
                </div>
                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body">
                <p class="lead">
                    Sending your comment...
                </p>
            </div>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
  // Show the toast
  $('.toast').toast('show');
});
</script>
<script src="{% static 'js/live_toast.js' %}"></script>
<br><br>
{% include 'baseshop_footer.html' %}
</body>
</html>

the_shop/theorders/templates/comment_approval.html
Hi {{ name }},

Your comment " {{ comment }} " has been received and is being assessed for posting. If approved it will be posted at the testimonial area at home-page https://topgz-ebby.up.railway.app/

Note:
    - Comment Approval might take up-to 7 days


Happy Shopping!!
Warm regards,
The Top Gz team

Have any questions??
topgz.ebby@gmail.com
https://www.linkedin.com/in/zebbylion-njau/
https://wa.me/+254773253606

Follow Top Gz socials to get notified on the latest trends available:
https://www.linkedin.com/in/zebbylion-njau/
https://twitter.com/zebby_G
https://github.com/zebbyG/
https://medium.com/@ZebbyG


THIS EMAIL IS AUTO-GENERATED AND YOU SHOULD NOT REPLY

the_shop/theorders/templates/order_completed.html
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>ORDER COMPLETED</title>
  <link rel="stylesheet" href="{% static 'css/page-header.css' %}">
  <link rel="shortcut icon" href="{% static 'logo.ico' %}" type="image/x-icon">
</head>
<body>
{% include 'bootstrap.html' %}
{% include 'backToTop.html' %} <!--Back to Top button -->
<br><br>
<div class="custom-container">
    <h3 class="display-3">
        <strong>Order Placed successfully</strong><!-- page-header.css for custom container styling -->
    </h3>
</div>
<br>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-3">
            <div class="alert alert-info">
                <em>
                    An order confirmation email has been sent...<br>Check email
                </em>
                <br><br>
                <small><a href="{% url 'orders:my_orders' %}" style="text-decoration: none;">My orders</a></small>
            </div>
        </div>
    </div>
</div>
<br><br>
{% include 'baseshop_footer.html' %}
</body>
</html>